export const database = {
  "graves": [
    {
      position: {
        x: 10,
        y:0,
        z: 0,
      },
      text: "Dylan Rieder",
      name: "Dylan",
      surname: "Rieder",
      color: null,
      age: 50,
      birthDate: "1973-06-10",
      deathDate: "2023-02-15",
    },
    {
      position: {
        x: 124,
        y:0,
        z: 0,
      },
      text: "Emily Johnson",
      name: "Emily",
      surname: "Johnson",
      color: "#"+((1<<24)*Math.random()|0).toString(16),
      age: 78,
      birthDate: "1945-09-22",
      deathDate: "2024-07-07",
    },
    {
      position: {
        x: 10,
        y:0,
        z: 0,
      },
      text: "Dylan Rieder",
      name: "Dylan",
      surname: "Rieder",
      color: null,
      age: 50,
      birthDate: "1973-06-10",
      deathDate: "2023-02-15",
    },
    {
      position: {
        x: 124,
        y:0,
        z: 0,
      },
      text: "Emily Johnson",
      name: "Emily",
      surname: "Johnson",
      color: "#"+((1<<24)*Math.random()|0).toString(16),
      age: 78,
      birthDate: "1945-09-22",
      deathDate: "2024-07-07",
    },
    {
      position: {
        x: 10,
        y:0,
        z: 0,
      },
      text: "Dylan Rieder",
      name: "Dylan",
      surname: "Rieder",
      color: null,
      age: 50,
      birthDate: "1973-06-10",
      deathDate: "2023-02-15",
    },
    {
      position: {
        x: 124,
        y:0,
        z: 0,
      },
      text: "Emily Johnson",
      name: "Emily",
      surname: "Johnson",
      color: "#"+((1<<24)*Math.random()|0).toString(16),
      age: 78,
      birthDate: "1945-09-22",
      deathDate: "2024-07-07",
    },
    {
      position: {
        x: 267,
        y:0,
        z: 0,
      },
      text: "Michael Williams",
      name: "Michael",
      surname: "Williams",
      color: null,
      age: 32,
      birthDate: "1991-03-17",
      deathDate: "2023-12-29",
    },
    {
      position: {
        x: -83,
        y:0,
        z: 0,
      },
      text: "Olivia Brown",
      name: "Olivia",
      surname: "Brown",
      color: "#"+((1<<24)*Math.random()|0).toString(16),
      age: 92,
      birthDate: "1931-12-02",
      deathDate: "2024-03-11",
    },
    {
      position: {
        x: -210,
        y:0,
        z: 0,
      },
      text: "James Miller",
      name: "James",
      surname: "Miller",
      color: null,
      age: 64,
      birthDate: "1959-08-18",
      deathDate: "2024-10-24",
    },
    {
      position: {
        x: 32,
        y:0,        z: 0,
      },
      text: "Sophia Davis",
      name: "Sophia",
      surname: "Davis",
      color: "#"+((1<<24)*Math.random()|0).toString(16),
      age: 78,
      birthDate: "1945-07-11",
      deathDate: "2024-09-05",
    },
    {
      position: {
        x: 399,
        y:0,        z: 0,
      },
      text: "Robert Anderson",
      name: "Robert",
      surname: "Anderson",
      color: null,
      age: 22,
      birthDate: "2001-02-27",
      deathDate: "2023-08-09",
    },
    {
      position: {
        x: -189,
        y:0,        z: 0,
      },
      text: "Emma Wilson",
      name: "Emma",
      surname: "Wilson",
      color: null,
      age: 18,
      birthDate: "2006-11-03",
      deathDate: "2024-01-28",
    },
    {
      position: {
        x: -346,
        y:0,        z: 0,
      },
      text: "Daniel Taylor",
      name: "Daniel",
      surname: "Taylor",
      color: "#"+((1<<24)*Math.random()|0).toString(16),
      age: 45,
      birthDate: "1978-09-01",
      deathDate: "2023-10-19",
    },
    {
      position: {
        x: 61,
        y:0,        z: 0,
      },
      text: "Ava Martinez",
      name: "Ava",
      surname: "Martinez",
      color: null,
      age: 89,
      birthDate: "1938-09-01",
      deathDate: "2023-10-19",
    },
    {
      position: {
        x: 10,
        y:0,        z: 0,
      },
      text: "John Smith",
      name: "John",
      surname: "Smith",
      color: null,
      age: 50,
      birthDate: "1973-06-10",
      deathDate: "2023-02-15",
    },
    {
      position: {
        x: 124,
        y:0,        z: 0,
      },
      text: "Emily Johnson",
      name: "Emily",
      surname: "Johnson",
      color: "#"+((1<<24)*Math.random()|0).toString(16),
      age: 78,
      birthDate: "1945-09-22",
      deathDate: "2024-07-07",
    },
    {
      position: {
        x: 267,
        y:0,        z: 0,
      },
      text: "Michael Williams",
      name: "Michael",
      surname: "Williams",
      color: null,
      age: 32,
      birthDate: "1991-03-17",
      deathDate: "2023-12-29",
    },
    {
      position: {
        x: -83,
        y:0,        z: 0,
      },
      text: "Olivia Brown",
      name: "Olivia",
      surname: "Brown",
      color: "#"+((1<<24)*Math.random()|0).toString(16),
      age: 92,
      birthDate: "1931-12-02",
      deathDate: "2024-03-11",
    },
    {
      position: {
        x: -210,
        y:0,        z: 0,
      },
      text: "James Miller",
      name: "James",
      surname: "Miller",
      color: null,
      age: 64,
      birthDate: "1959-08-18",
      deathDate: "2024-10-24",
    },
    {
      position: {
        x: 32,
        y:0,        z: 0,
      },
      text: "Sophia Davis",
      name: "Sophia",
      surname: "Davis",
      color: "#"+((1<<24)*Math.random()|0).toString(16),
      age: 78,
      birthDate: "1945-07-11",
      deathDate: "2024-09-05",
    },
    {
      position: {
        x: 399,
        y:0,        z: 0,
      },
      text: "Robert Anderson",
      name: "Robert",
      surname: "Anderson",
      color: null,
      age: 22,
      birthDate: "2001-02-27",
      deathDate: "2023-08-09",
    },
    {
      position: {
        x: -189,
        y:0,        z: 0,
      },
      text: "Emma Wilson",
      name: "Emma",
      surname: "Wilson",
      color: null,
      age: 18,
      birthDate: "2006-11-03",
      deathDate: "2024-01-28",
    },
    {
      position: {
        x: -346,
        y:0,        z: 0,
      },
      text: "Daniel Taylor",
      name: "Daniel",
      surname: "Taylor",
      color: "#"+((1<<24)*Math.random()|0).toString(16),
      age: 45,
      birthDate: "1978-09-01",
      deathDate: "2023-10-19",
    },
    {
      position: {
        x: 61,
        y:0,        z: 0,
      },
      text: "Ava Martinez",
      name: "Ava",
      surname: "Martinez",
      color: null,
      age: 89,
      birthDate: "1938-09-01",
      deathDate: "2023-10-19",
    },
  ],
};